"""empty message

Revision ID: ffda23b073ed
Revises: d34289ed94ca
Create Date: 2018-11-02 13:40:59.228951

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'ffda23b073ed'
down_revision = 'd34289ed94ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('updateTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hoges', sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False))
    op.create_foreign_key('parent_id_fk', 'hoges', 'parents', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('parent_id_fk', 'hoges', type_='foreignkey')
    op.drop_column('hoges', 'parent_id')
    op.drop_table('parents')
    # ### end Alembic commands ###
